server:
   port: 8888
   servlet:
      context-path: "/api"
spring:
   datasource:
      url: jdbc:h2:mem:spring-boot-cafe
      driver-class-name: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: create-drop